env:
  global:
  - secure: lSjiLjzub7amf+h0XEvT1wWkn0qmWj/A+8nj1Iipb+YrZJZZvogcqYyNQ3aFDVAxZSKnqYbgDZyPHUYU2FO1o6l70k461FyBkXmolb2eEsh1LRwhmm33mzn5fGGvivOqZmgFbMzZJi7sSJq1/Px719aiMtbmcnabRFHPsXwDqoF5T5NSVu8q8gNjiNkjDr9sOZcNjDLIqV1AiprRIKzwFlmIP8vSuoBgJGd4yBBUkhYs6gimHs+0RdfR63oSa/0c52pDoYCPEMflQc/p81+GpND2JAtHEkGi+FcDqfNmBBDPsC+ZZxwJjudydCCNIvTY90oRqJ9wteGniWgUYVyFRNjFJvKCgLxKh0a4PXqKkKPuRAXWkFVfM6sWq02mwG2/+P3TgDBxeRvI452gXowqkyJWoR5HAmXu8e5TlKcLYp9UXZOATOMbjFaPBSoHFs6acPMKGMpoPz68az/NTL/KQv5W/vaI1aWAkUAoiFt+ZOq9x00gCJnZfynxiW9+rXuTHGbdkiaPxaAuTUab/Mnni9KIDIvTqpYG12+uCxAAEEsTY+mDxjPO7atL4frwnZXRAZriWiWYBgm3OqP5UxW9jGGHJnmQfWQMnsTMEuq8oq2U7xt917p/wko73zKc4CN22LoRltZBDUSlfFu+/zfRuMcLD0wDePNFN8s6An/1eUE=
language:
  - shell
script:
- ./post-build.sh
